### ISSUE TITLE
Техническое задание

### ISSUE THREAD

**Issue by suhininalex** [GreenTeamSpbStu/SharedAccessList#1]
Сформировать список сущностей и действий над ними.

**Comment by SemenMartynov** [comment]
Народ, у вас задачи очень не однородные...
- Получить сертификат и прикрепить к серверу можно объединить в один milestone, 
- Задачи вида "Ознакомится с ..." на имеют конкретной измеримой цели,
- А вот "Создать необходимые приложения в vkontakte и gmail" можно вовсю декомпозировать.

**Comment by suhininalex** [comment]
1) Из того, что я помню, получить сертификат - это боль. А интегрировать его с сервером, еще более. Вероятно, это только в первый раз, но тем не менее.
2) Задачи типа ознакомится необходимы для фиксации занятости человека. На знакомство с hessian может понадобиться пол дня или более. Мне бы хотелось видеть, на что тратиться время.
3) Создавать приложения как раз минутное дело. Декомпозиция ради декомпозиции не имеет смысла.

Спасибо за твое видинье, но прошу не вмешиваться непосредственно в проект. Ты можешь задать вопрос или высказать предложение кому-то конкретно, чтобы не захламлять задачи.

**Comment by suhininalex** [comment]
Первая версия есть. Сегодня уточню у Ицыксона.
