### ISSUE TITLE
Определить сервер для web-интерфейсов.

### ISSUE THREAD

**Issue by suhininalex** [GreenTeamSpbStu/SharedAccessList#12]
Посмотреть как подключить к нему сертификат.

**Comment by nxt007** [comment]
Поясни, чем это отличается от задания для Игоря?

**Comment by suhininalex** [comment]
Игорь будет работать, вероятно, с серваком, который я писал в том семестре.
Тебе нужно выбрать сервак на котором будут висеть мобильный и обычный сайты.
(Ты что-то говорил про nanohttpd?)
Добавь страницу на вики, кто за сервак, почему он. (Пиши как можно меньше, но чтоб я или, например, Лаура поняли почему именно он. 
Посмотри как подключить к нему сертификат.

**Comment by suhininalex** [comment]
Просто LAMP сервер.
