### ISSUE TITLE
Нотификация не удаляется по accept, даже если она не валидна

### ISSUE THREAD

**Issue by nxt007** [GreenTeamSpbStu/SharedAccessList#24]
Лог сервера
May 07, 2015 4:36:00 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
WARN: SQL Error: 1062, SQLState: 23000
May 07, 2015 4:36:00 PM org.hibernate.engine.jdbc.spi.SqlExceptionHelper logExceptions
ERROR: Duplicate entry '1-62' for key 'FK_GROUPID'
May 07, 2015 4:36:00 PM org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl release
INFO: HHH000010: On release of batch it still contained JDBC statements

**Comment by nxt007** [comment]
Edit: по deny все удаляется

**Comment by suhininalex** [comment]
Если возвращается ошибка User already participates this group! Приглашение все равно удаляется

**Comment by suhininalex** [comment]
Всё тлен и не работает
