### ISSUE TITLE
Определить общую структуру БД.

### ISSUE THREAD

**Issue by suhininalex** [GreenTeamSpbStu/SharedAccessList#8]
Определить структуру БД. Оформить соответствующую страницу на wiki.

**Comment by SemenMartynov** [comment]
Задачи нужно составить в какую-то иерархию, для этого тут есть milestone.
Нельзя заниматься проектированием БД пока не будут сформулированы функциональные требования и не будут вычленены сущности.

---

UPD: А, сори, понял как вы решили организовать задачи. Но мне всё равно кажется слишком большой кусок пытаетесь за раз откусить))

**Comment by suhininalex** [comment]
1) Некоторые задачи на данный момент нельзя делать, т.к. нет ТЗ. Необходимо дождаться.
2) Текущие задачи расчитаны не на одну неделю. Задача выдается когда ее можно определить, даже если для ее решения чего-то не хватает. Я надеюсь, это поможет людям расчитывать время.
3) Если чего-то будем не успевать, перенесем на след. неделю. Удобно разбить все, на недели, т.к. именно за неделю (выходные?) можно что-то сделать или НЕ СДЕЛАТЬ и увидеть это.

**Comment by suhininalex** [comment]
Реализуй это через что-то похожее на IbExpert для быстрого получения скрипта, который развернет бд, в случае ее утверждения.
Результат зафиксируй в Wiki и старайся поддерживать эту страницу в актуальном состоянии.
